name: CI

on:
  push:
    branches:
      - main
      - testcoverage
  pull_request:
    branches:
      - main
      - testcoverage

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage
        continue-on-error: true   

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}